# Generated by Django 3.1.6 on 2021-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0002_auto_20210209_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название заказа')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('animal', models.ManyToManyField(related_name='order_animal', to='pet_shop.Animal', verbose_name='Кличка питомца')),
                ('user', models.ManyToManyField(related_name='order_user', to='pet_shop.User', verbose_name='Зозяин питомца')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
