# Generated by Django 3.1.6 on 2021-02-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='animal',
        ),
        migrations.AddField(
            model_name='order',
            name='animal',
            field=models.CharField(default=123, max_length=50, verbose_name='Кличка'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=123, max_length=50, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
